In [1]:
from pandas import Series
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = [10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0, 100.0]
series = Series(data)

In [3]:
series

0     10.0
1     20.0
2     30.0
3     40.0
4     50.0
5     60.0
6     70.0
7     80.0
8     90.0
9    100.0
dtype: float64

In [4]:
# prepare data for normalization
values = series.values
values = values.reshape((len(values), 1))

In [5]:
values

array([[ 10.],
       [ 20.],
       [ 30.],
       [ 40.],
       [ 50.],
       [ 60.],
       [ 70.],
       [ 80.],
       [ 90.],
       [100.]])

In [7]:
# train the normalization
scaler = MinMaxScaler(feature_range=(0, 1))
scaler = scaler.fit(values)

In [8]:
scaler.data_min_

array([10.])

In [9]:
scaler.data_max_

array([100.])

In [11]:
# normalize the dataset and print
normalized = scaler.transform(values)
normalized

array([[0.        ],
       [0.11111111],
       [0.22222222],
       [0.33333333],
       [0.44444444],
       [0.55555556],
       [0.66666667],
       [0.77777778],
       [0.88888889],
       [1.        ]])

In [12]:
# inverse transform and print
inversed = scaler.inverse_transform(normalized)
inversed

array([[ 10.],
       [ 20.],
       [ 30.],
       [ 40.],
       [ 50.],
       [ 60.],
       [ 70.],
       [ 80.],
       [ 90.],
       [100.]])