In [1]:
from pandas import Series
from sklearn.preprocessing import StandardScaler
from math import sqrt

In [2]:
# define contrived series
data = [1.0, 5.5, 9.0, 2.6, 8.8, 3.0, 4.1, 7.9, 6.3]
series = Series(data)

In [3]:
series

0    1.0
1    5.5
2    9.0
3    2.6
4    8.8
5    3.0
6    4.1
7    7.9
8    6.3
dtype: float64

In [4]:
# prepare data for normalization
values = series.values
values = values.reshape((len(values), 1))

In [5]:
values

array([[1. ],
       [5.5],
       [9. ],
       [2.6],
       [8.8],
       [3. ],
       [4.1],
       [7.9],
       [6.3]])

In [6]:
# train the normalization
scaler = StandardScaler()
scaler = scaler.fit(values)

In [7]:
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [8]:
scaler.mean_

array([5.35555556])

In [9]:
scaler.var_

array([7.35802469])

In [10]:
sqrt(scaler.var_)

2.7125679146074897

In [11]:
# normalize the dataset and print
standardized = scaler.transform(values)

In [12]:
standardized

array([[-1.60569456],
       [ 0.05325007],
       [ 1.34354035],
       [-1.01584758],
       [ 1.26980948],
       [-0.86838584],
       [-0.46286604],
       [ 0.93802055],
       [ 0.34817357]])

In [13]:
# inverse transform and print
inversed = scaler.inverse_transform(standardized)

In [14]:
inversed

array([[1. ],
       [5.5],
       [9. ],
       [2.6],
       [8.8],
       [3. ],
       [4.1],
       [7.9],
       [6.3]])